### PR TITLE
Added !important

### PR DESCRIPTION
**Pull request by NeXTs**
Added !important to css animation rule.

With this plugin I want to remove from the DOM inserts made by Chrome extensions.
But some of them adds style="all:initial" to the added element which overrides animation rule and this plugin does not detect added elements.

!important should solve the problem without any negative consequences.

### CODE REVIEW

**Comment by NeXTs** [comment]
Or, if you wish, it could be added as an option to the config.

insertionQ.config({
    strictlyNew : true,
    timeout : 20,
    addImportant: true
});

**Comment by naugtur** [comment]
I'd like it to be configurable so that the default behavior doesn't change and I don't need to bump major version.

**Comment by NeXTs** [comment]
@naugtur ok, added it to the config

**Comment by naugtur** [comment]
When contributing to opensource packages avoid changing version numbers. They often have their automation for that and if not, at least opinions on what to set.

I know you wanted to do more work to help me. No harm done. 
I intend to bump minor, so I'll need some manual work here and can't merge with one click on the phone.

Anyway, thanks for this contribution. I'll merge it soon and release.
I'm happy insertionQuery is useful for you.

**Comment by NeXTs** [comment]
Got it

**Comment by NeXTs** [comment]
Any update?

**Comment by naugtur** [comment]
Too much life, not enough time at the keyboard. 
Maybe tonight.

**Comment by NeXTs** [comment]
Cool, thanks!
btw I've missed it in PR, but here's few bytes saver `animation-duration:` `0.001s` => `1ms`

**Pull request merged**
